trigger:
- master

pool:
  vmImage: ubuntu-latest
  name: 'brandon'

steps:
- task: bnicoll oak9 Analysis Task@2.0.129
  inputs:
    serviceEndpoint: 'oak9 dev'
    projectName: 'proj-bgnicollf74f045d7-26'
    environmentName: 'env-bgnicollf74f045d7-0JOW7Ugg'
    qualityGate: 'None'
    pollingTimeoutSec: '300'
    oak9APIEndpoint: http://localhost:5000
