trigger:
- master

pool:
  vmImage: ubuntu-latest
  name: 'brandon'

steps:
- task: oak9
  inputs:
    serviceEndpoint: 'oak9 Integration Testing'
    projectName: 'proj-bgnicollf74f045d7-26'
    environmentName: 'env-bgnicollf74f045d7-0JOW7Ugg'
    qualityGate: 'None'
    pollingTimeoutSec: '300'
    oak9APIEndpoint: https://devapi.oak9.cloud